# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'SpaceIn' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpaceIn
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'GoogleSignIn'
  pod 'Shimmer', '~> 1.0'

end
